feed:
  name: Feed Pet
  description: Trigger a manual feeding event.
  fields:
    portions:
      description: Number of portions to feed
      example: 1
      required: true
      default: 1
ligth:
  name: Toggle Light
  description: Toggle the feeder's light on or off.
  fields:
    state:
      description: Desired state of the light (on/off)
      example: "on"
      required: true
