dispense:
  name: Dispense Portion
  description: Dispense a portion of food from the pet feeder.
  fields:
    amount:
      name: Amount
      description: Number of portions to dispense.
      required: false
      example: 2
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: box
